### ISSUE TITLE
decryptMedia not working

### ISSUE THREAD

**Issue by sanep10** [smashah/wa-decrypt#1]
I speak in spanish, sorry if my english is'n correct

In the decrypt.ts file

![Captura de pantalla de 2020-01-23 12-20-49](https://user-images.githubusercontent.com/46332292/73007620-d4c3fb80-3dda-11ea-953b-5b1ea710ac29.png)

in this part: 
![Captura de pantalla de 2020-01-23 12-21-39](https://user-images.githubusercontent.com/46332292/73007663-ec02e900-3dda-11ea-97e1-5fe8ba8c0b92.png)

I never get a response with statusCode 200

My code is this:
![Captura de pantalla de 2020-01-23 12-22-23](https://user-images.githubusercontent.com/46332292/73007738-105ec580-3ddb-11ea-9972-318ccbe1f800.png)

**Comment by smashah** [comment]
Hey @sanep10 since you're already using sulla-hotfix you should import it from there instead of using wa-decrypt.

**Comment by sanep10** [comment]
@smashah Thanks for replying!!!

If i use decryptMedia directly of sulla-hotfix, my app dont make anything too.
Doesn't show any message in the console, no write any file and no send any image.

**Comment by sanep10** [comment]
I only have the code that stay in the picture, i don't know if i have an error. But in the console don't show any error.

My console:
![Captura de pantalla de 2020-01-23 14-23-56](https://user-images.githubusercontent.com/46332292/73016535-06918e00-3dec-11ea-8f75-3020e3c33db6.png)

This screenshot was take it after send an image to session of Whatsapp authenticated.

**Comment by jona950** [comment]
Hi there.
you must do this:

const generatedUa = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.77 Safari/537.36'; // just copy and paste.

const mediaData = await decryptMedia(message,generatedUa); // and add second parameter.

I hope you help.

**Comment by sanep10** [comment]
@jona950 Thanks for replying!!!
Effectively this code are the solution
Thanks so much!
