### ISSUE TITLE
trouble qr code

### ISSUE THREAD

**Issue by jona950** [smashah/wa-decrypt#2]
Hi everyone!
the trouble is when access for second time to the app.
this example is with simple message (like the example webpage)
if i remove session folder and ask me to qr code scan works...
but when the session exist and no qr code needed there is the trouble : 
so first time works, en second time no works.
thanks!
![image](https://user-images.githubusercontent.com/7121836/73357130-c443d300-4269-11ea-99f1-85fb13a5b442.png)

**Comment by smashah** [comment]
unrelated to this repo
